const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_23_42_07_18_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTY4LFxuICAgICAgICAxOTQsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTAsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTExLFxuICAgICAgICA3LFxuICAgICAgICA4NixcbiAgICAgICAgMjU0LFxuICAgICAgICAxMjUsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTk5LFxuICAgICAgICA4OSxcbiAgICAgICAgMTcxLFxuICAgICAgICAxMzEsXG4gICAgICAgIDIxOCxcbiAgICAgICAgNzcsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjU1LFxuICAgICAgICAxMjEsXG4gICAgICAgIDYyLFxuICAgICAgICAxOTMsXG4gICAgICAgIDE4MixcbiAgICAgICAgMjM5LFxuICAgICAgICAyMTQsXG4gICAgICAgIDg4LFxuICAgICAgICAxODIsXG4gICAgICAgIDg4LFxuICAgICAgICAxNTksXG4gICAgICAgIDY0LFxuICAgICAgICA3MyxcbiAgICAgICAgOTFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODQsXG4gICAgICAgIDE1MixcbiAgICAgICAgMjAzLFxuICAgICAgICAyMyxcbiAgICAgICAgMjI4LFxuICAgICAgICAxNDMsXG4gICAgICAgIDEzMixcbiAgICAgICAgOTksXG4gICAgICAgIDIxLFxuICAgICAgICA1MixcbiAgICAgICAgODksXG4gICAgICAgIDkyLFxuICAgICAgICAxNzQsXG4gICAgICAgIDg1LFxuICAgICAgICAxNzMsXG4gICAgICAgIDIwLFxuICAgICAgICAxODQsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTQsXG4gICAgICAgIDcyLFxuICAgICAgICAxNTQsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTk0LFxuICAgICAgICAxNzcsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMjAzLFxuICAgICAgICA0OSxcbiAgICAgICAgNjksXG4gICAgICAgIDIwLFxuICAgICAgICAyNixcbiAgICAgICAgMTksXG4gICAgICAgIDcyXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNjgsXG4gICAgICAgIDU1LFxuICAgICAgICAxODcsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjEyLFxuICAgICAgICA2MSxcbiAgICAgICAgMjUwLFxuICAgICAgICAxODgsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTY0LFxuICAgICAgICA0NyxcbiAgICAgICAgMTM0LFxuICAgICAgICAyMSxcbiAgICAgICAgMTY0LFxuICAgICAgICA4OSxcbiAgICAgICAgMjE0LFxuICAgICAgICAxNTAsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTEzLFxuICAgICAgICAxNDcsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjE2LFxuICAgICAgICA4NixcbiAgICAgICAgMjI1LFxuICAgICAgICAyMixcbiAgICAgICAgMTEwLFxuICAgICAgICAyMyxcbiAgICAgICAgMTM5LFxuICAgICAgICAyMjAsXG4gICAgICAgIDEzNixcbiAgICAgICAgNTgsXG4gICAgICAgIDExOVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMDksXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTAwLFxuICAgICAgICAzMCxcbiAgICAgICAgMTA4LFxuICAgICAgICAxMjIsXG4gICAgICAgIDUxLFxuICAgICAgICAxNTEsXG4gICAgICAgIDc1LFxuICAgICAgICAxMjMsXG4gICAgICAgIDE3MCxcbiAgICAgICAgNixcbiAgICAgICAgMTA4LFxuICAgICAgICAyNDcsXG4gICAgICAgIDE3NixcbiAgICAgICAgMjA0LFxuICAgICAgICA5OSxcbiAgICAgICAgNDMsXG4gICAgICAgIDg0LFxuICAgICAgICAxMTYsXG4gICAgICAgIDUyLFxuICAgICAgICAxOCxcbiAgICAgICAgMjU0LFxuICAgICAgICAxMTIsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTI1LFxuICAgICAgICAxNDEsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTYsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjA2LFxuICAgICAgICA4NFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTUyLFxuICAgICAgICAxMCxcbiAgICAgICAgMjUzLFxuICAgICAgICAxMTksXG4gICAgICAgIDExNCxcbiAgICAgICAgNjksXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjQ4LFxuICAgICAgICA5NCxcbiAgICAgICAgMTE2LFxuICAgICAgICAyMDgsXG4gICAgICAgIDI0LFxuICAgICAgICAyMTAsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMzEsXG4gICAgICAgIDU3LFxuICAgICAgICAyMDYsXG4gICAgICAgIDQ4LFxuICAgICAgICA3NyxcbiAgICAgICAgMjUwLFxuICAgICAgICAxODAsXG4gICAgICAgIDY4LFxuICAgICAgICA4MCxcbiAgICAgICAgMTQwLFxuICAgICAgICA2MSxcbiAgICAgICAgMTk3LFxuICAgICAgICAxMDcsXG4gICAgICAgIDExMSxcbiAgICAgICAgOSxcbiAgICAgICAgMTUwLFxuICAgICAgICA2OCxcbiAgICAgICAgMTExXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDExNyxcbiAgICAgICAgMTU3LFxuICAgICAgICAxMDQsXG4gICAgICAgIDU4LFxuICAgICAgICAxNjYsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTk3LFxuICAgICAgICAyMjksXG4gICAgICAgIDc4LFxuICAgICAgICAxNjIsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAyMDQsXG4gICAgICAgIDE1NixcbiAgICAgICAgODksXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTYsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTg5LFxuICAgICAgICA4MixcbiAgICAgICAgOTgsXG4gICAgICAgIDY2LFxuICAgICAgICAyMzYsXG4gICAgICAgIDQ4LFxuICAgICAgICAxMTYsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTE4LFxuICAgICAgICAxNTMsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMzYsXG4gICAgICAgIDI0NyxcbiAgICAgICAgNFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICA1NSxcbiAgICAgICAgICAyMCxcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAzMyxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICAzNixcbiAgICAgICAgICAyMzgsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMjIwLFxuICAgICAgICAgIDE5NSxcbiAgICAgICAgICAxNixcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgNjdcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICA0NixcbiAgICAgICAgICAyNixcbiAgICAgICAgICA5MyxcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMTMxLFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDExMixcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgOSxcbiAgICAgICAgICAxMjVcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA5MixcbiAgICAgICAgNjMsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTI1LFxuICAgICAgICA3NSxcbiAgICAgICAgMTkzLFxuICAgICAgICAyNDcsXG4gICAgICAgIDExMSxcbiAgICAgICAgOTgsXG4gICAgICAgIDI0MixcbiAgICAgICAgMjI2LFxuICAgICAgICAyMDEsXG4gICAgICAgIDExNSxcbiAgICAgICAgMTAzLFxuICAgICAgICA5MCxcbiAgICAgICAgMCxcbiAgICAgICAgNDEsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTk1LFxuICAgICAgICAxMDUsXG4gICAgICAgIDE1MixcbiAgICAgICAgMjA3LFxuICAgICAgICAyNDQsXG4gICAgICAgIDEzMyxcbiAgICAgICAgODgsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMjMzLFxuICAgICAgICA2MyxcbiAgICAgICAgNTgsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTY5LFxuICAgICAgICAyMDYsXG4gICAgICAgIDgyLFxuICAgICAgICAxMzIsXG4gICAgICAgIDMwLFxuICAgICAgICA4NCxcbiAgICAgICAgMTAzLFxuICAgICAgICAyNDEsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTc2LFxuICAgICAgICAyMCxcbiAgICAgICAgOTYsXG4gICAgICAgIDQ3LFxuICAgICAgICAxMjQsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTIsXG4gICAgICAgIDE4NSxcbiAgICAgICAgODIsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMjQwLFxuICAgICAgICAxNzMsXG4gICAgICAgIDE4MCxcbiAgICAgICAgMTEsXG4gICAgICAgIDAsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTA3LFxuICAgICAgICA5MSxcbiAgICAgICAgMTY0LFxuICAgICAgICAxMzUsXG4gICAgICAgIDY1LFxuICAgICAgICAyNyxcbiAgICAgICAgMjIzLFxuICAgICAgICAxNDksXG4gICAgICAgIDEzMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogNDMsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiY3RmM1kzQWRnNVIrL1oyQVhpNzhJNEQzVmdGbkI0TTNJZHBaUEhyRVZDST1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ3MDE4Nzg5MjA1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIzRTFGMEM2NzI2NDE1NTIzMzM2MjcyRUNCOTJBREMzN1wiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjEzNDYxMjNcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiUHVuaS1XZTlSZjJFZnQ2ZzFJWEFpZ1wiLFxuICBcInBob25lSWRcIjogXCJhNmE2MzA1MC1hMTExLTQzZjQtOTQ4ZS05OWE5ZjAzOTFlODNcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjE5LFxuICAgICAgMTc1LFxuICAgICAgMjA1LFxuICAgICAgMTg3LFxuICAgICAgMTQ0LFxuICAgICAgNDksXG4gICAgICA5OCxcbiAgICAgIDk0LFxuICAgICAgMTQxLFxuICAgICAgMTc5LFxuICAgICAgMjAzLFxuICAgICAgNjksXG4gICAgICAyMTIsXG4gICAgICAxOTMsXG4gICAgICAxOSxcbiAgICAgIDM5LFxuICAgICAgMzQsXG4gICAgICAyNTIsXG4gICAgICAxOTQsXG4gICAgICAyMDNcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgOTIsXG4gICAgICAxNDQsXG4gICAgICAyMTAsXG4gICAgICA4LFxuICAgICAgMTQ3LFxuICAgICAgMjE3LFxuICAgICAgNTQsXG4gICAgICAxNDksXG4gICAgICAyMzIsXG4gICAgICA4MixcbiAgICAgIDEzLFxuICAgICAgOTgsXG4gICAgICAxNzcsXG4gICAgICAyNTUsXG4gICAgICAxNDMsXG4gICAgICAxODMsXG4gICAgICAzLFxuICAgICAgNDMsXG4gICAgICAyMDQsXG4gICAgICA3NFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCIyVFBBQzlEN1wiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0NzAxODc4OTIwNToyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxNjQ2MzA4Nzc5NzA0NTk6MkBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNNeThxTk1ERU1IUTVyUUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIkV1Y2dVRCsxaDd6UHNrUnltWUNCN29pd1BvRGtJWGRMWE42NHFDNmRuWDQ9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwid3UxSW5KekN0VjNNaHJuZE43RFVlMHgzMW1Pa1RLQmwwanpETUl6bnVFOGl0VUlJUWlTTFJ0eFJEVzdFRGlOUStub0lJVjhvVHAxTEJ6UXRja1B1QlE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwieFMxUXpvdHhtZ2toNitaSWJzeE4weUdOQkF1a3pwNG9RcXR1ZTNmNi93VEUyZGwwVUNEZEdBUm42TlQrRGswd29BTEtkaW82blFUaXJLckcyZ2t5aGc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0NzAxODc4OTIwNToyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTY4LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgMTI2XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjEzNDYxMTYsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFBeVFcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUF5US5qc29uIjogIntcImtleURhdGFcIjpcIktLMVk4QW90ZlRjeEpENmtsdnl4WWhSdncwOFhyb1JpVFlwQkxjclVEbHc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6OTgwMDMzMDk5LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
